### ISSUE TITLE
Is there a .predict() function for every single model?

### ISSUE THREAD

**Issue by 1Biaohe** [hengzhe-zhang/scikit-rtdl#3]
Hi, 

Thanks for your work on the development.
What I'd like to know is whether there is a .predict() function for [FTTransformerRegressor, MLPRegressor, ResNetRegressor, DCNV2Regressor] or how to do the prediction. Because after I accomplished the model training, I'd like to do some prediction work. But I didn't find the prediction function in the document.

Thanks!

**Comment by hengzhe-zhang** [comment]
Of course, you can use the `.predict()` function for all these regressors. All these regressors inherit the class `MLPBase`, which implements the `.predict()` function.

**Comment by 1Biaohe** [comment]
hi,
Thanks for the reply.

But I'm still confused.  When I implement the code, I instantiated the class: FTTransformerRegressor at first and then used the predict() function, but it didn't work, and showed the error, as shown in the image.

So could you please give me some code examples to show how to use the predict()?  
Since I read the code document and there is no .predict() function in the class: FTTransformerRegressor.

Many thanks!

![error](https://user-images.githubusercontent.com/88216557/178699760-50967f7b-b909-4dcf-8ed2-e8c42ead6553.png)

**Comment by hengzhe-zhang** [comment]
Sorry, it's my fault. I don't return a regressor object after calling the `".fit()"` function. One quick solution is to instantiate the model in a separate line. I will fix this issue as soon as possible.

**Comment by 1Biaohe** [comment]
Thanks for your time and consideration!

**Comment by 1Biaohe** [comment]
hi

According to your comment: 'One quick solution is to instantiate the model in a separate line', I did one change like the image shown. Now, the .predict() function worked. Is it correct?

Thanks!

![image](https://user-images.githubusercontent.com/88216557/178709365-53f488af-d88e-4e4f-b415-07d6dd26e778.png)

**Comment by hengzhe-zhang** [comment]
@1Biaohe Hi, it seems I missed your message. So sorry for that. Your change is correct, and now I have officially changed my code to that.  Thanks for proposing such an issue. Cheers!

**Comment by 1Biaohe** [comment]
> @1Biaohe Hi, it seems I missed your message. So sorry for that. Your change is correct, and now I have officially changed my code to that. Thanks for proposing such an issue. Cheers!

That's great! Thanks for your time.
